name: "AWS Access"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read # needed for private repos to checkout

jobs:
  read-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::717727228533:role/sts-lab-2-target
          role-session-name: OIDCSession

      - run: aws secretsmanager get-secret-value --secret-id flag_sts_lab_2
        shell: bash
