{
on:
  workflow_dispatch:
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "sts:TagSession",
        "sts:AssumeRoleWithWebIdentity"
      ],
      "Principal": {
        "Federated": "arn:aws:iam::717727228533:oidc-provider/token.actions.githubusercontent.com"
      },
      "Condition": {
        "StringEquals": {
          "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
        },
        "StringLike": {
          "token.actions.githubusercontent.com:sub": "repo:*/hacktricks-training*"
        }
      }
    }
  ]
}
